// Mocks generated by Mockito 5.4.6 from annotations
// in mongolite/test/presentation/providers/connection_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mongolite/data/repositories/mongo_repository.dart' as _i5;
import 'package:mongolite/data/services/mongo_connection_service.dart' as _i2;
import 'package:mongolite/data/services/secure_storage_service.dart' as _i4;
import 'package:mongolite/domain/models/mongo_collection.dart' as _i7;
import 'package:mongolite/domain/models/mongo_database.dart' as _i6;
import 'package:mongolite/domain/models/mongo_document.dart' as _i8;
import 'package:mongolite/presentation/providers/database_provider.dart' as _i9;
import 'package:mongolite/presentation/providers/document_provider.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MongoConnectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMongoConnectionService extends _i1.Mock
    implements _i2.MongoConnectionService {
  MockMongoConnectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i3.Future<void> connect(String? uri) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [uri]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getDatabaseNames() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabaseNames, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> getCollectionNames(String? databaseName) =>
      (super.noSuchMethod(
            Invocation.method(#getCollectionNames, [databaseName]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getDocuments({
    required String? databaseName,
    required String? collectionName,
    Map<String, dynamic>? filter,
    int? skip = 0,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDocuments, [], {
              #databaseName: databaseName,
              #collectionName: collectionName,
              #filter: filter,
              #skip: skip,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> countDocuments({
    required String? databaseName,
    required String? collectionName,
    Map<String, dynamic>? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countDocuments, [], {
              #databaseName: databaseName,
              #collectionName: collectionName,
              #filter: filter,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> insertDocument({
    required String? databaseName,
    required String? collectionName,
    required Map<String, dynamic>? document,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertDocument, [], {
              #databaseName: databaseName,
              #collectionName: collectionName,
              #document: document,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateDocument({
    required String? databaseName,
    required String? collectionName,
    required dynamic documentId,
    required Map<String, dynamic>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDocument, [], {
              #databaseName: databaseName,
              #collectionName: collectionName,
              #documentId: documentId,
              #updates: updates,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDocument({
    required String? databaseName,
    required String? collectionName,
    required dynamic documentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [], {
              #databaseName: databaseName,
              #collectionName: collectionName,
              #documentId: documentId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i4.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveConnectionConfig({
    required String? uri,
    String? alias,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveConnectionConfig, [], {
              #uri: uri,
              #alias: alias,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String?>> loadConnectionConfig() =>
      (super.noSuchMethod(
            Invocation.method(#loadConnectionConfig, []),
            returnValue: _i3.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i3.Future<Map<String, String?>>);

  @override
  _i3.Future<void> clearConnectionConfig() =>
      (super.noSuchMethod(
            Invocation.method(#clearConnectionConfig, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> hasSavedConnection() =>
      (super.noSuchMethod(
            Invocation.method(#hasSavedConnection, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [MongoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMongoRepository extends _i1.Mock implements _i5.MongoRepository {
  MockMongoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.MongoDatabaseInfo>> getDatabases() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabases, []),
            returnValue: _i3.Future<List<_i6.MongoDatabaseInfo>>.value(
              <_i6.MongoDatabaseInfo>[],
            ),
          )
          as _i3.Future<List<_i6.MongoDatabaseInfo>>);

  @override
  _i3.Future<List<_i7.MongoCollectionInfo>> getCollections(
    String? databaseName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCollections, [databaseName]),
            returnValue: _i3.Future<List<_i7.MongoCollectionInfo>>.value(
              <_i7.MongoCollectionInfo>[],
            ),
          )
          as _i3.Future<List<_i7.MongoCollectionInfo>>);

  @override
  _i3.Future<List<_i8.MongoDocument>> getDocuments({
    required String? database,
    required String? collection,
    Map<String, dynamic>? filter,
    int? skip = 0,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDocuments, [], {
              #database: database,
              #collection: collection,
              #filter: filter,
              #skip: skip,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i8.MongoDocument>>.value(
              <_i8.MongoDocument>[],
            ),
          )
          as _i3.Future<List<_i8.MongoDocument>>);

  @override
  _i3.Future<int> countDocuments({
    required String? database,
    required String? collection,
    Map<String, dynamic>? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countDocuments, [], {
              #database: database,
              #collection: collection,
              #filter: filter,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> insertDocument(_i8.MongoDocument? document) =>
      (super.noSuchMethod(
            Invocation.method(#insertDocument, [document]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateDocument({
    required String? database,
    required String? collection,
    required dynamic documentId,
    required Map<String, dynamic>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDocument, [], {
              #database: database,
              #collection: collection,
              #documentId: documentId,
              #updates: updates,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDocument({
    required String? database,
    required String? collection,
    required dynamic documentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [], {
              #database: database,
              #collection: collection,
              #documentId: documentId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [DatabaseProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseProvider extends _i1.Mock implements _i9.DatabaseProvider {
  MockDatabaseProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.MongoDatabaseInfo> get databases =>
      (super.noSuchMethod(
            Invocation.getter(#databases),
            returnValue: <_i6.MongoDatabaseInfo>[],
          )
          as List<_i6.MongoDatabaseInfo>);

  @override
  List<_i7.MongoCollectionInfo> get collections =>
      (super.noSuchMethod(
            Invocation.getter(#collections),
            returnValue: <_i7.MongoCollectionInfo>[],
          )
          as List<_i7.MongoCollectionInfo>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> loadDatabases() =>
      (super.noSuchMethod(
            Invocation.method(#loadDatabases, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> loadCollections(String? databaseName) =>
      (super.noSuchMethod(
            Invocation.method(#loadCollections, [databaseName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void clearData() => super.noSuchMethod(
    Invocation.method(#clearData, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DocumentProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentProvider extends _i1.Mock implements _i11.DocumentProvider {
  MockDocumentProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.MongoDocument> get documents =>
      (super.noSuchMethod(
            Invocation.getter(#documents),
            returnValue: <_i8.MongoDocument>[],
          )
          as List<_i8.MongoDocument>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  int get currentPage =>
      (super.noSuchMethod(Invocation.getter(#currentPage), returnValue: 0)
          as int);

  @override
  int get totalPages =>
      (super.noSuchMethod(Invocation.getter(#totalPages), returnValue: 0)
          as int);

  @override
  int get totalDocuments =>
      (super.noSuchMethod(Invocation.getter(#totalDocuments), returnValue: 0)
          as int);

  @override
  bool get hasMore =>
      (super.noSuchMethod(Invocation.getter(#hasMore), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> loadDocuments({
    required String? database,
    required String? collection,
    bool? reset = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadDocuments, [], {
              #database: database,
              #collection: collection,
              #reset: reset,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> loadNextPage() =>
      (super.noSuchMethod(
            Invocation.method(#loadNextPage, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void setFilter(Map<String, dynamic>? filter) => super.noSuchMethod(
    Invocation.method(#setFilter, [filter]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> applyFilterAndReload() =>
      (super.noSuchMethod(
            Invocation.method(#applyFilterAndReload, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDocument(_i8.MongoDocument? document) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [document]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void clearDocuments() => super.noSuchMethod(
    Invocation.method(#clearDocuments, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
