// Mocks generated by Mockito 5.4.6 from annotations
// in mongolite/test/presentation/providers/database_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mongolite/data/repositories/mongo_repository.dart' as _i2;
import 'package:mongolite/domain/models/mongo_collection.dart' as _i5;
import 'package:mongolite/domain/models/mongo_database.dart' as _i4;
import 'package:mongolite/domain/models/mongo_document.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MongoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMongoRepository extends _i1.Mock implements _i2.MongoRepository {
  MockMongoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MongoDatabaseInfo>> getDatabases() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabases, []),
            returnValue: _i3.Future<List<_i4.MongoDatabaseInfo>>.value(
              <_i4.MongoDatabaseInfo>[],
            ),
          )
          as _i3.Future<List<_i4.MongoDatabaseInfo>>);

  @override
  _i3.Future<List<_i5.MongoCollectionInfo>> getCollections(
    String? databaseName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCollections, [databaseName]),
            returnValue: _i3.Future<List<_i5.MongoCollectionInfo>>.value(
              <_i5.MongoCollectionInfo>[],
            ),
          )
          as _i3.Future<List<_i5.MongoCollectionInfo>>);

  @override
  _i3.Future<List<_i6.MongoDocument>> getDocuments({
    required String? database,
    required String? collection,
    Map<String, dynamic>? filter,
    int? skip = 0,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDocuments, [], {
              #database: database,
              #collection: collection,
              #filter: filter,
              #skip: skip,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i6.MongoDocument>>.value(
              <_i6.MongoDocument>[],
            ),
          )
          as _i3.Future<List<_i6.MongoDocument>>);

  @override
  _i3.Future<int> countDocuments({
    required String? database,
    required String? collection,
    Map<String, dynamic>? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countDocuments, [], {
              #database: database,
              #collection: collection,
              #filter: filter,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> insertDocument(_i6.MongoDocument? document) =>
      (super.noSuchMethod(
            Invocation.method(#insertDocument, [document]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateDocument({
    required String? database,
    required String? collection,
    required dynamic documentId,
    required Map<String, dynamic>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDocument, [], {
              #database: database,
              #collection: collection,
              #documentId: documentId,
              #updates: updates,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDocument({
    required String? database,
    required String? collection,
    required dynamic documentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [], {
              #database: database,
              #collection: collection,
              #documentId: documentId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
